
package com.mescoe.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MescoeWebService", targetNamespace = "http://webservice.mescoe.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MescoeWebService {


    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.util.List<com.mescoe.webservice.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListOfStudentFromMescoe", targetNamespace = "http://webservice.mescoe.com/", className = "com.mescoe.webservice.GetListOfStudentFromMescoe")
    @ResponseWrapper(localName = "getListOfStudentFromMescoeResponse", targetNamespace = "http://webservice.mescoe.com/", className = "com.mescoe.webservice.GetListOfStudentFromMescoeResponse")
    @Action(input = "http://webservice.mescoe.com/MescoeWebService/getListOfStudentFromMescoeRequest", output = "http://webservice.mescoe.com/MescoeWebService/getListOfStudentFromMescoeResponse")
    public List<Student> getListOfStudentFromMescoe(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        float arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        float arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        float arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        int arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        int arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        int arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        List<String> arg13);

}
